// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvz0y-eQ9oiYj30FqU6tkfNQO-KLRS3WU',
    appId: '1:902364881984:android:b92033fbb638505ac4aba5',
    messagingSenderId: '902364881984',
    projectId: 'esp32-sensor-6ec3b',
    databaseURL: 'https://esp32-sensor-6ec3b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'esp32-sensor-6ec3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPgp7DLJ6Lgl5n1EoNNsbGpMsr7kXy3Pg',
    appId: '1:902364881984:ios:639eb60d8aa41800c4aba5',
    messagingSenderId: '902364881984',
    projectId: 'esp32-sensor-6ec3b',
    databaseURL: 'https://esp32-sensor-6ec3b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'esp32-sensor-6ec3b.appspot.com',
    iosBundleId: 'com.control.sensorControlFront',
  );
}
